feat(no-use-watch): Add rule prohibiting use of watch
andykao1213/eslint-plugin-react-hook-form pull request #26
Opened 2024-11-17 10:39 UTC by tatsuya-asami

A new rule prohibiting the use of watch has been added.

Since there are cases where values are not updated when the React compiler and watch are used together, the use of watch is prohibited and useWatch should always be used.

https://github.com/react-hook-form/react-hook-form/issues/11910

2025-01-14 06:22 UTC, Grawl commented
the same problem is with `formState`

2025-01-14 07:39 UTC, Grawl commented
Not works for this code:

```ts
const form = useForm();
const { watch } = form;
```

This works:

```js
    overrides: [
      {
        files: ['./src/**/*.tsx'],
        rules: {
          'no-restricted-properties': [
            'error',
            {
              property: 'watch',
              message: 'Not works with React Compiler. Use useFormWatch instead.',
            },
            {
              property: 'formState',
              message: 'Not works with React Compiler. Use useFormState instead.',
            },
          ],
        },
      },
    ],
```

I put it in `tsx`' `overrides` to apply only for components because I use Effector which also use `watch` method (also not recommended by Effector linter 😄 )

2025-05-10 05:00 UTC, andykao1213 requested changes
@tatsuya-asami 
I apologize for the late response; there's no excuse for me. I really appreciate your PR and it really brings value to the users. The PR is already in a good shape, but let's make it even better:

**Check the object destruction of `useForm` return value**
@Grawl pointed out a good use case where the `watch` may be destructed later in another variable:
```js
const form = useForm();
const { watch } = form;
```
I think it's worth to handle the case in the PR, here's my thought for your reference:
```diff
index c809763..9527fe4 100644
--- a/lib/rules/no-use-watch.js
+++ b/lib/rules/no-use-watch.js
@@ -29,7 +29,10 @@ module.exports = {
     // Helpers
     //----------------------------------------------------------------------
 
-    function check(node) {
+    // Store variables that were initialized with useForm or useFormContext
+    const formContextVars = new Set();
+
+    function checkCallExpression(node) {
       if (
         node.type === "VariableDeclarator" &&
         node.init?.type === "CallExpression" &&
@@ -37,6 +40,9 @@ module.exports = {
           node.init?.callee.name === "useFormContext")
       ) {
         if (node.id.type === "Identifier") {
+          // Add the variable to our tracking set
+          formContextVars.add(node.id.name);
+          
           const formMethodsVar = context.getScope().set.get(node.id.name);
           formMethodsVar.references.forEach((formMethodsReference) => {
             const { parent } = formMethodsReference.identifier;
@@ -64,12 +70,33 @@ module.exports = {
       }
     }
 
+    function checkDestructuring(node) {
+      // Check for destructuring from a tracked form context variable
+      if (
+        node.type === "VariableDeclarator" &&
+        node.init?.type === "Identifier" &&
+        formContextVars.has(node.init.name) &&
+        node.id.type === "ObjectPattern"
+      ) {
+        const watchProperty = findPropertyByName(node, "watch");
+        if (watchProperty?.value.type === "Identifier") {
+          context.report({
+            node: watchProperty.value,
+            messageId: "useUseWatch",
+          });
+        }
+      }
+    }
+
     //----------------------------------------------------------------------
     // Public
     //----------------------------------------------------------------------
 
     return {
-      VariableDeclarator: check,
+      VariableDeclarator(node) {
+        checkCallExpression(node);
+        checkDestructuring(node);
+      },
     };
   },
 };
 ```
 
 **Typo**
 As the Copilot pointed out, there are some typos in the tests. Please fix it to make the test better!

2025-05-10 05:42 UTC, tatsuya-asami commented
@andykao1213 @Grawl 
Thank you for your review.
I will review your comment and try to correct it!

2025-05-10 06:12 UTC, tatsuya-asami commented
> the same problem is with `formState`

Thank you for your comment. In my experience formState works fine.
Also, I will not change anything about formState in this pull request, as it would be better to create that rule separately!

2025-05-10 06:14 UTC, tatsuya-asami commented
> **Check the object destruction of `useForm` return value** @Grawl pointed out a good use case where the `watch` may be destructed later in another variable:

The code you suggested worked perfectly, so we adopted it as is. Thank you very much!
I revised my typo as well!

2025-05-11 14:09 UTC, andykao1213 approved these changes
Looks good to me! Thanks for the contribution

2025-05-11 14:09 UTC, merged